const fs = require('fs');
let file = fs.readFileSync('frontend/src/pages/fixed-assets/FixedAssetDetailPage.tsx', 'utf8');

file = file.replace(
    "<div><span className=\"text-neutral-500\">Residual Value:</span> <span className=\"text-neutral-800 ml-1 font-medium\">{formatMoney(asset.residual_value_centavos)}</span></div>\n          </div>\n        </div>\n      </div>",
    "<div><span className=\"text-neutral-500\">Residual Value:</span> <span className=\"text-neutral-800 ml-1 font-medium\">{formatMoney(asset.residual_value_centavos)}</span></div>\n          </div>\n        </div>\n      </div>\n\n      <div className=\"mt-8 bg-white border border-neutral-200 rounded-lg p-6\">\n        <h3 className=\"text-lg font-medium text-neutral-800 mb-4\">Depreciation Schedule</h3>\n        {(!asset.depreciation_entries || asset.depreciation_entries.length === 0) ? (\n          <p className=\"text-neutral-500 text-sm\">No depreciation entries recorded yet.</p>\n        ) : (\n          <div className=\"overflow-x-auto\">\n            <table className=\"w-full text-sm text-left\">\n              <thead className=\"text-xs text-neutral-500 bg-neutral-50 border-b border-neutral-200\">\n                <tr>\n                  <th className=\"px-4 py-3 font-medium\">Date</th>\n                  <th className=\"px-4 py-3 font-medium\">Period</th>\n                  <th className=\"px-4 py-3 font-medium text-right\">Amount</th>\n                  <th className=\"px-4 py-3 font-medium text-right\">Book Value</th>\n                </tr>\n              </thead>\n              <tbody className=\"divide-y divide-neutral-100\">\n                {asset.depreciation_entries.map((entry: any) => (\n                  <tr key={entry.id}>\n                    <td className=\"px-4 py-3 text-neutral-800\">{entry.entry_date}</td>\n                    <td className=\"px-4 py-3 text-neutral-600\">{entry.fiscal_period?.name || '—'}</td>\n                    <td className=\"px-4 py-3 text-red-600 font-medium text-right\">\n                      - {formatMoney(entry.amount_centavos)}\n                    </td>\n                    <td className=\"px-4 py-3 text-neutral-800 font-medium text-right\">\n                      {formatMoney(entry.book_value_after_centavos)}\n                    </td>\n                  </tr>\n                ))}\n              </tbody>\n            </table>\n          </div>\n        )}\n      </div>"
);

fs.writeFileSync('frontend/src/pages/fixed-assets/FixedAssetDetailPage.tsx', file);
