<?php

declare(strict_types=1);

use App\Domains\Mold\Models\MoldMaster;
use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;

uses(RefreshDatabase::class);
uses()->group('feature', 'mold');

beforeEach(function () {
    $this->seed(\Database\Seeders\RolePermissionSeeder::class);
    $this->seed(\Database\Seeders\ModuleSeeder::class);
    $this->seed(\Database\Seeders\ModulePermissionSeeder::class);
    $this->seed(\Database\Seeders\DepartmentPositionSeeder::class);
    $this->seed(\Database\Seeders\DepartmentModuleAssignmentSeeder::class);

    $prodDept = \App\Domains\HR\Models\Department::where('code', 'PROD')->first();
    $this->manager = User::factory()->create();
    $this->manager->assignRole('manager');
    $this->manager->departments()->attach($prodDept->id, ['is_primary' => true]);
});

it('lists molds', function () {
    $this->actingAs($this->manager)
        ->getJson('/api/v1/mold/molds')
        ->assertOk()
        ->assertJsonStructure(['data']);
});

it('creates a mold', function () {
    $response = $this->actingAs($this->manager)
        ->postJson('/api/v1/mold/molds', [
            'mold_code'       => 'MLD-TEST-001',
            'name'            => 'Test Mold',
            'type'            => 'injection',
            'cavity_count'    => 2,
            'max_shot_count'  => 100000,
            'current_shot_count' => 0,
            'status'          => 'active',
        ]);
    
    $response->assertCreated();
    // Verify response has mold data (mold_code may be auto-generated by DB trigger)
    $response->assertJsonStructure(['data' => ['id', 'mold_code', 'name', 'status']]);
});
