<?php

declare(strict_types=1);

use App\Domains\HR\Models\Department;
use App\Models\User;
use Database\Seeders\DepartmentModuleAssignmentSeeder;
use Database\Seeders\DepartmentPositionSeeder;
use Database\Seeders\ModulePermissionSeeder;
use Database\Seeders\ModuleSeeder;
use Database\Seeders\RolePermissionSeeder;
use Illuminate\Foundation\Testing\RefreshDatabase;

uses(RefreshDatabase::class);
uses()->group('feature', 'mold');

beforeEach(function () {
    $this->seed(RolePermissionSeeder::class);
    $this->seed(ModuleSeeder::class);
    $this->seed(ModulePermissionSeeder::class);
    $this->seed(DepartmentPositionSeeder::class);
    $this->seed(DepartmentModuleAssignmentSeeder::class);

    $prodDept = Department::where('code', 'PROD')->first();
    $this->manager = User::factory()->create();
    $this->manager->assignRole('manager');
    $this->manager->departments()->attach($prodDept->id, ['is_primary' => true]);
});

it('lists molds', function () {
    $this->actingAs($this->manager)
        ->getJson('/api/v1/mold/molds')
        ->assertOk()
        ->assertJsonStructure(['data']);
});

it('creates a mold', function () {
    $response = $this->actingAs($this->manager)
        ->postJson('/api/v1/mold/molds', [
            'mold_code' => 'MLD-TEST-001',
            'name' => 'Test Mold',
            'type' => 'injection',
            'cavity_count' => 2,
            'max_shot_count' => 100000,
            'current_shot_count' => 0,
            'status' => 'active',
        ]);

    $response->assertCreated();
    // Verify response has mold data (mold_code may be auto-generated by DB trigger)
    $response->assertJsonStructure(['data' => ['id', 'mold_code', 'name', 'status']]);
});
