<?php

declare(strict_types=1);

namespace App\Domains\Loan\Services;

use App\Domains\Accounting\Models\ChartOfAccount;
use App\Domains\Accounting\Models\JournalEntry;
use App\Domains\Accounting\Models\JournalEntryLine;
use App\Domains\Accounting\Services\FiscalPeriodService;
use App\Domains\HR\Models\Employee;
use App\Domains\Loan\Models\Loan;
use App\Domains\Loan\Models\LoanType;
use App\Models\User;
use App\Notifications\LoanAccountingApprovedNotification;
use App\Notifications\LoanApprovedNotification;
use App\Notifications\LoanCancelledNotification;
use App\Notifications\LoanDisbursedNotification;
use App\Notifications\LoanRequestedNotification;
use App\Notifications\LoanWrittenOffNotification;
use App\Shared\Contracts\ServiceContract;
use App\Shared\Exceptions\DomainException;
use App\Shared\Exceptions\SodViolationException;
use Illuminate\Pagination\LengthAwarePaginator;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Notification;

/**
 * Loan request lifecycle service.
 *
 * Business rules:
 *  LN-001: Employee cannot have two active loans of the same type simultaneously.
 *  LN-002: Principal cannot exceed max_amount_centavos for the loan type.
 *  LN-003: SSS Loan eligibility — ≥ 36 months posted SSS contributions (stub for Phase 1C).
 *  LN-004: Pag-IBIG Loan eligibility — ≥ 24 months posted Pag-IBIG contributions (stub for Phase 1C).
 *  LN-005: Monthly amortization computed by LoanAmortizationService on approval.
 *  LN-006: Schedule generated by LoanAmortizationService on approval.
 *  LN-008: Skipped installments do not accrue penalty by default.
 *  LN-009: On write-off, flag remaining balance for HR review.
 *  LN-010: SoD — approved_by must differ from requested_by.
 */
final class LoanRequestService implements ServiceContract
{
    // Chart of account codes for loan transactions
    private const string ACCT_LOANS_RECEIVABLE = '1200';

    private const string ACCT_LOANS_PAYABLE = '2104';

    private const string ACCT_CASH_IN_BANK = '1001';

    public function __construct(
        private readonly LoanAmortizationService $amortizationService,
        private readonly FiscalPeriodService $fiscalPeriodService,
    ) {}

    /**
     * List loans with optional filters.
     *
     * @param  array<string, mixed>  $filters
     */
    public function list(array $filters = [], int $perPage = 25): LengthAwarePaginator
    {
        $query = Loan::with(['employee', 'loanType'])
            ->latest();

        if (isset($filters['employee_id'])) {
            $query->where('employee_id', $filters['employee_id']);
        }

        if (isset($filters['status'])) {
            $query->where('status', $filters['status']);
        }

        if (isset($filters['loan_type_id'])) {
            $query->where('loan_type_id', $filters['loan_type_id']);
        }

        return $query->paginate($perPage);
    }

    /**
     * Get loan history for an employee (past and pending loans).
     *
     * @return \Illuminate\Database\Eloquent\Collection<int, Loan>
     */
    public function getEmployeeLoanHistory(int $employeeId, ?int $excludeLoanId = null): \Illuminate\Database\Eloquent\Collection
    {
        $query = Loan::with(['loanType'])
            ->where('employee_id', $employeeId)
            ->whereNotIn('status', ['cancelled', 'rejected'])
            ->orderByDesc('created_at');

        if ($excludeLoanId !== null) {
            $query->where('id', '!=', $excludeLoanId);
        }

        return $query->get();
    }

    /**
     * Submit a new loan application.
     *
     * @param  array<string, mixed>  $data
     *
     * @throws DomainException
     */
    public function submit(Employee $employee, array $data, int $requestedByUserId): Loan
    {
        $loan = DB::transaction(function () use ($employee, $data, $requestedByUserId): Loan {
            $loanType = LoanType::findOrFail($data['loan_type_id']);

            // LN-001: No active loan of any type (regardless of loan type)
            $this->assertNoActiveLoan($employee);

            // LN-002: Principal within allowed range
            $principal = (int) $data['principal_centavos'];
            $this->assertPrincipalWithinLimits($loanType, $principal);

            // LN-003/LN-004: Government loan eligibility (stub — full check in Phase 1C)
            $this->assertGovernmentLoanEligibility($employee, $loanType);

            // Validate term
            if ($data['term_months'] > $loanType->max_term_months) {
                throw new DomainException(
                    sprintf(
                        'Term %d months exceeds maximum allowed %d months for %s.',
                        $data['term_months'],
                        $loanType->max_term_months,
                        $loanType->name,
                    ),
                    'LN_TERM_EXCEEDS_MAX',
                    422,
                );
            }

            $loan = Loan::create([
                'workflow_version' => 2,
                'reference_no' => $this->generateReferenceNo(),
                'employee_id' => $employee->id,
                'loan_type_id' => $loanType->id,
                'requested_by' => $requestedByUserId,
                'principal_centavos' => $principal,
                'term_months' => $data['term_months'],
                'interest_rate_annual' => $loanType->interest_rate_annual,
                'monthly_amortization_centavos' => 0,   // computed on approval
                'total_payable_centavos' => 0,   // computed on approval
                'outstanding_balance_centavos' => $principal,
                'loan_date' => now()->toDateString(),
                'first_deduction_date' => $data['first_deduction_date'] ?? null,
                'deduction_cutoff' => $data['deduction_cutoff'] ?? '2nd',
                'status' => 'pending',
                'purpose' => $data['purpose'] ?? null,
            ]);

            return $loan;
        });

        // Notify HR managers that a new loan application has been filed
        $this->notifyHrManagersOfNewLoan($loan);

        return $loan;
    }

    /**
     * HR Manager approval — generates amortization schedule.
     * LN-010: SoD — HR approver must differ from requester.
     *
     * @throws SodViolationException|DomainException
     */
    public function approve(
        Loan $loan,
        int $approvedByUserId,
        ?string $remarks = null,
        ?string $firstDeductionDate = null,
    ): Loan {
        // C4: Block v1 approval path for v2 workflow loans
        if ($loan->workflow_version === 2) {
            throw new DomainException(
                'This loan uses the v2 workflow. Use headNote() → managerCheck() → officerReview() → vpApprove().',
                'LN_WRONG_WORKFLOW_VERSION',
                409,
            );
        }

        // LN-010: SoD check - cannot be requester
        if ($loan->requested_by === $approvedByUserId) {
            throw new SodViolationException(
                'loan_application',
                'approve',
                'Loan approver must differ from requester (LN-010).',
            );
        }

        if ($loan->status !== 'pending') {
            throw new DomainException(
                'Only pending loans can be HR-approved.',
                'LN_NOT_PENDING',
                422,
            );
        }

        $loan = DB::transaction(function () use ($loan, $approvedByUserId, $remarks, $firstDeductionDate): Loan {
            $firstDue = $firstDeductionDate
                ? Carbon::parse($firstDeductionDate)
                : Carbon::today()->startOfMonth()->addMonth();

            $loan->approved_by = $approvedByUserId;
            $loan->approver_remarks = $remarks;
            $loan->approved_at = now();
            $loan->first_deduction_date = $firstDue;
            $loan->status = 'approved';
            $loan->save();

            // LN-005 + LN-006: Compute amortization and generate schedule
            $this->amortizationService->generateSchedule($loan);

            return $loan->fresh();
        });

        // Notify accounting managers that a loan is awaiting their approval
        $this->notifyAccountingManagersOfLoanApproval($loan);

        return $loan;
    }

    // ── Workflow v2 methods ───────────────────────────────────────────────────

    /** Assert the loan is on the given workflow version or throw. */
    private function assertWorkflowVersion(Loan $loan, int $version): void
    {
        if ($loan->workflow_version !== $version) {
            throw new DomainException(
                "This action requires workflow version {$version}.",
                'LN_WRONG_WORKFLOW_VERSION',
                422,
            );
        }
    }

    /**
     * Stage 1 (v2): Department Head notes the loan application.
     *
     * @throws DomainException
     */
    public function headNote(Loan $loan, int $headUserId, string $remarks = ''): Loan
    {
        $this->assertWorkflowVersion($loan, 2);

        if ($loan->status !== 'pending') {
            throw new DomainException(
                'Only pending loans can be head-noted.',
                'LN_NOT_PENDING',
                422,
            );
        }

        $loan->head_noted_by = $headUserId;
        $loan->head_noted_at = now();
        $loan->head_remarks = $remarks ?: null;
        $loan->status = 'head_noted';
        $loan->save();

        return $loan->fresh();
    }

    /**
     * Stage 2 (v2): Manager checks the head-noted loan.
     * SoD: checker must differ from head who noted.
     *
     * @throws SodViolationException|DomainException
     */
    public function managerCheck(Loan $loan, int $managerUserId, string $remarks = ''): Loan
    {
        $this->assertWorkflowVersion($loan, 2);

        if ($loan->head_noted_by === $managerUserId) {
            throw new SodViolationException(
                'loan_manager_check',
                'check',
                'Manager checker must differ from Department Head (SoD).',
            );
        }

        if ($loan->status !== 'head_noted') {
            throw new DomainException(
                'Only head-noted loans can be manager-checked.',
                'LN_NOT_HEAD_NOTED',
                422,
            );
        }

        $loan->manager_checked_by = $managerUserId;
        $loan->manager_checked_at = now();
        $loan->manager_remarks = $remarks ?: null;
        $loan->status = 'manager_checked';
        $loan->save();

        return $loan->fresh();
    }

    /**
     * Stage 3 (v2): Officer reviews the manager-checked loan.
     *
     * @throws DomainException
     */
    public function officerReview(Loan $loan, int $officerUserId, string $remarks = ''): Loan
    {
        $this->assertWorkflowVersion($loan, 2);

        if ($loan->status !== 'manager_checked') {
            throw new DomainException(
                'Only manager-checked loans can be officer-reviewed.',
                'LN_NOT_MANAGER_CHECKED',
                422,
            );
        }

        $loan->officer_reviewed_by = $officerUserId;
        $loan->officer_reviewed_at = now();
        $loan->officer_remarks = $remarks ?: null;
        $loan->status = 'officer_reviewed';
        $loan->save();

        return $loan->fresh();
    }

    /**
     * Stage 4 (v2): VP approves and triggers amortization schedule generation.
     * SoD: VP must differ from officer reviewer.
     *
     * @throws SodViolationException|DomainException
     */
    public function vpApprove(
        Loan $loan,
        int $vpUserId,
        string $remarks = '',
        ?string $firstDeductionDate = null,
    ): Loan {
        $this->assertWorkflowVersion($loan, 2);

        if ($loan->officer_reviewed_by === $vpUserId) {
            throw new SodViolationException(
                'loan_vp_approval',
                'approve',
                'VP approver must differ from Officer reviewer (SoD).',
            );
        }

        if ($loan->status !== 'officer_reviewed') {
            throw new DomainException(
                'Only officer-reviewed loans can be VP-approved.',
                'LN_NOT_OFFICER_REVIEWED',
                422,
            );
        }

        $loan = DB::transaction(function () use ($loan, $vpUserId, $remarks, $firstDeductionDate): Loan {
            $firstDue = $firstDeductionDate
                ? Carbon::parse($firstDeductionDate)
                : Carbon::today()->startOfMonth()->addMonth();

            $loan->vp_approved_by = $vpUserId;
            $loan->vp_approved_at = now();
            $loan->vp_remarks = $remarks ?: null;
            $loan->first_deduction_date = $firstDue;
            $loan->status = 'ready_for_disbursement';
            $loan->save();

            // Generate amortization schedule (same as v1 accountingApprove)
            $this->amortizationService->generateSchedule($loan);

            return $loan->fresh();
        });

        return $loan;
    }

    /**
     * Accounting Manager approval — verifies funds and creates GL entry.
     * LN-011: SoD — accounting approver must differ from HR approver.
     *
     * @throws SodViolationException|DomainException
     */
    public function accountingApprove(
        Loan $loan,
        int $accountingManagerId,
        ?string $remarks = null,
    ): Loan {
        // C4: Block v1 accounting approval path for v2 workflow loans
        if ($loan->workflow_version === 2) {
            throw new DomainException(
                'This loan uses the v2 workflow. Use the v2 accounting approval method.',
                'LN_WRONG_WORKFLOW_VERSION',
                409,
            );
        }

        // LN-011: SoD check
        if ($loan->approved_by === $accountingManagerId) {
            throw new SodViolationException(
                'loan_accounting_approval',
                'approve',
                'Accounting approver must differ from HR approver (LN-011).',
            );
        }

        if ($loan->status !== 'approved') {
            throw new DomainException(
                'Only HR-approved loans can be sent to Accounting.',
                'LN_NOT_HR_APPROVED',
                422,
            );
        }

        $loan = DB::transaction(function () use ($loan, $accountingManagerId, $remarks): Loan {
            $loan->accounting_approved_by = $accountingManagerId;
            $loan->accounting_remarks = $remarks;
            $loan->accounting_approved_at = now();
            $loan->status = 'ready_for_disbursement';
            $loan->save();

            // Create GL entry for loan receivable
            $this->createLoanGlEntry($loan);

            return $loan->fresh();
        });

        // Notify HR approver that accounting has signed off
        $this->notifyOfAccountingApproval($loan);

        return $loan;
    }

    /**
     * Create GL journal entry for loan on accounting approval.
     * Debit: Loans Receivable - Employee (Asset)
     * Credit: Loans Payable - Employee (Liability - pending disbursement)
     *
     * JE-001: Entry is balanced (debits = credits)
     * JE-008: source_type = 'loan', source_id = loan->id
     */
    private function createLoanGlEntry(Loan $loan): void
    {
        $principalPesos = $loan->principal_centavos / 100;
        $date = now()->toDateString();
        $description = "Loan receivable - {$loan->reference_no} - {$loan->employee->full_name}";

        // Get fiscal period for the date
        $fiscalPeriod = $this->fiscalPeriodService->resolveForDateOrFail(Carbon::parse($date));

        // Get account IDs from chart of accounts
        $loansReceivableAcct = ChartOfAccount::where('code', self::ACCT_LOANS_RECEIVABLE)->first();
        $loansPayableAcct = ChartOfAccount::where('code', self::ACCT_LOANS_PAYABLE)->first();

        if (! $loansReceivableAcct || ! $loansPayableAcct) {
            throw new DomainException(
                'Required loan accounts not found in chart of accounts. '.
                'Please ensure accounts 1200 (Loans Receivable) and 2104 (Loans Payable) exist.',
                'LN_GL_ACCOUNTS_MISSING',
                500,
            );
        }

        // Create journal entry as draft first (trigger checks balance only on posted JEs)
        $je = JournalEntry::create([
            'date' => $date,
            'description' => $description,
            'source_type' => 'loan',
            'source_id' => $loan->id,
            'status' => 'draft',
            'fiscal_period_id' => $fiscalPeriod->id,
            'created_by' => auth()->id(),
            'submitted_by' => auth()->id(),
        ]);

        // Debit: Loans Receivable (Asset increase)
        JournalEntryLine::create([
            'journal_entry_id' => $je->id,
            'account_id' => $loansReceivableAcct->id,
            'debit' => $principalPesos,
            'credit' => null,
            'description' => "Loan principal - {$loan->reference_no}",
        ]);

        // Credit: Loans Payable (Liability increase - obligation to disburse)
        JournalEntryLine::create([
            'journal_entry_id' => $je->id,
            'account_id' => $loansPayableAcct->id,
            'debit' => null,
            'credit' => $principalPesos,
            'description' => "Loan payable pending disbursement - {$loan->reference_no}",
        ]);

        // Auto-post now that both lines are in place (balance trigger will pass)
        $je->update([
            'status' => 'posted',
            'je_number' => "JE-{$date}-LN{$loan->id}",
            'posted_by' => null,  // system auto-post — SoD allows NULL
            'posted_at' => now(),
        ]);

        // Link loan to journal entry
        $loan->journal_entry_id = $je->id;
        $loan->save();
    }

    /**
     * Update GL entry on disbursement to reflect cash outflow.
     * Creates a new JE: Debit Loans Payable, Credit Cash
     */
    private function updateGlEntryForDisbursement(Loan $loan): void
    {
        $principalPesos = $loan->principal_centavos / 100;
        $date = now()->toDateString();
        $description = "Loan disbursement - {$loan->reference_no} - {$loan->employee->full_name}";

        // Get fiscal period for the date
        $fiscalPeriod = $this->fiscalPeriodService->resolveForDateOrFail(Carbon::parse($date));

        // Get account IDs
        $loansPayableAcct = ChartOfAccount::where('code', self::ACCT_LOANS_PAYABLE)->first();
        $cashAcct = ChartOfAccount::where('code', self::ACCT_CASH_IN_BANK)->first();

        if (! $loansPayableAcct || ! $cashAcct) {
            throw new DomainException(
                'Required accounts not found in chart of accounts. '.
                'Please ensure accounts 2104 (Loans Payable) and 1001 (Cash in Bank) exist.',
                'LN_GL_ACCOUNTS_MISSING',
                500,
            );
        }

        // Create disbursement journal entry as draft first (balance trigger fires on posted JEs)
        $je = JournalEntry::create([
            'date' => $date,
            'description' => $description,
            'source_type' => 'loan',
            'source_id' => $loan->id,
            'status' => 'draft',
            'fiscal_period_id' => $fiscalPeriod->id,
            'created_by' => auth()->id(),
            'submitted_by' => auth()->id(),
        ]);

        // Debit: Loans Payable (Liability decrease - obligation cleared)
        JournalEntryLine::create([
            'journal_entry_id' => $je->id,
            'account_id' => $loansPayableAcct->id,
            'debit' => $principalPesos,
            'credit' => null,
            'description' => "Loan disbursement - {$loan->reference_no}",
        ]);

        // Credit: Cash in Bank (Asset decrease - funds released)
        JournalEntryLine::create([
            'journal_entry_id' => $je->id,
            'account_id' => $cashAcct->id,
            'debit' => null,
            'credit' => $principalPesos,
            'description' => "Cash disbursed for loan {$loan->reference_no}",
        ]);

        // Auto-post now that both lines are in place (balance trigger will pass)
        $je->update([
            'status' => 'posted',
            'je_number' => "JE-{$date}-LN{$loan->id}-DISB",
            'posted_by' => null,  // system auto-post — SoD allows NULL
            'posted_at' => now(),
        ]);
    }

    /**
     * Disburse an approved loan — mark it active and release funds.
     * LN-012: Requires Accounting approval before disbursement.
     *
     * @throws DomainException
     */
    public function disburse(Loan $loan, int $disbursedByUserId): Loan
    {
        if ($loan->status !== 'ready_for_disbursement') {
            throw new DomainException(
                'Loan must be accounting-approved before disbursement.',
                'LN_NOT_ACCOUNTING_APPROVED',
                422,
            );
        }

        $loan = DB::transaction(function () use ($loan, $disbursedByUserId): Loan {
            $loan->status = 'active';
            $loan->disbursed_at = now();
            $loan->disbursed_by = $disbursedByUserId;
            $loan->save();

            // Create GL entry for cash disbursement
            $this->updateGlEntryForDisbursement($loan);

            return $loan;
        });

        // Notify the employee, HR approver, and Accounting approver that funds have been released
        $this->notifyAllPartiesOfDisbursement($loan);

        return $loan;
    }

    /**
     * Reject a pending loan application.
     * LN-010 SoD: reviewer must differ from requester.
     *
     * @throws SodViolationException|DomainException
     */
    public function reject(Loan $loan, int $reviewedByUserId, ?string $remarks = null): Loan
    {
        if ($loan->requested_by === $reviewedByUserId) {
            throw new SodViolationException(
                'loan_application',
                'reject',
                'Loan rejector must differ from requester (LN-010).',
            );
        }

        if (! $loan->isPending()) {
            throw new DomainException(
                'Only pending loans can be rejected.',
                'LN_NOT_PENDING',
                422,
            );
        }

        $loan->status = 'rejected';
        $loan->approved_by = $reviewedByUserId;
        $loan->approver_remarks = $remarks;
        $loan->approved_at = now();
        $loan->save();

        return $loan;
    }

    /**
     * Cancel a loan that is still pending or approved.
     *
     * @throws DomainException
     */
    public function cancel(Loan $loan, int $cancelledByUserId): Loan
    {
        if (! $loan->canBeCancelled()) {
            throw new DomainException(
                'Only loans that have not yet been approved by HR Manager can be cancelled.',
                'LN_CANNOT_CANCEL',
                422,
            );
        }

        $loan->status = 'cancelled';
        $loan->save();

        // Notify relevant parties of the cancellation
        $this->notifyOfLoanCancellation($loan);

        return $loan;
    }

    /**
     * Write off an active loan.
     * LN-009: Flags remaining balance for HR Manager review.
     * The write-off does NOT automatically deduct from final pay — that is done
     * by the Separation Service as a separate step.
     *
     * @throws DomainException
     */
    public function writeOff(Loan $loan): Loan
    {
        if (! $loan->isActive()) {
            throw new DomainException(
                'Only active loans can be written off.',
                'LN_NOT_ACTIVE',
                422,
            );
        }

        // LN-009: outstanding balance is preserved for audit trail
        $loan->status = 'written_off';
        $loan->save();

        // Notify HR and Accounting that the loan was written off and balance needs review (LN-009)
        $this->notifyOfLoanWriteOff($loan);

        return $loan;
    }

    // ── Private helpers ───────────────────────────────────────────────────────

    /**
     * Notify HR managers (users with loans.approve permission) that a loan was submitted.
     */
    private function notifyHrManagersOfNewLoan(Loan $loan): void
    {
        try {
            $hrManagers = User::permission('loans.approve')->get();
            if ($hrManagers->isNotEmpty()) {
                Notification::send($hrManagers, new LoanRequestedNotification($loan->loadMissing('employee', 'loanType')));
            }
        } catch (\Throwable) {
            // Non-fatal — notification failure must not block the loan submission
        }
    }

    /**
     * Notify the employee, HR approver, and Accounting approver that a loan has been disbursed.
     */
    private function notifyAllPartiesOfDisbursement(Loan $loan): void
    {
        try {
            $loan->loadMissing('employee', 'loanType');

            // Employee — their funds have been released
            $employeeUserId = $loan->employee->getAttribute('user_id');
            if ($employeeUserId) {
                User::find($employeeUserId)?->notify(new LoanDisbursedNotification($loan, 'employee'));
            }

            // HR Manager who approved the loan
            if ($loan->approved_by) {
                User::find($loan->approved_by)?->notify(new LoanDisbursedNotification($loan, 'hr'));
            }

            // Accounting Manager who cleared the loan for disbursement
            if ($loan->accounting_approved_by) {
                User::find($loan->accounting_approved_by)?->notify(new LoanDisbursedNotification($loan, 'accounting'));
            }
        } catch (\Throwable) {
            // Non-fatal
        }
    }

    /**
     * Notify Accounting Managers that a loan has been HR-approved and awaits their sign-off.
     */
    private function notifyAccountingManagersOfLoanApproval(Loan $loan): void
    {
        try {
            $acctgManagers = User::permission('loans.accounting_approve')
                ->where('id', '!=', $loan->approved_by)
                ->get();

            if ($acctgManagers->isNotEmpty()) {
                Notification::send(
                    $acctgManagers,
                    new LoanApprovedNotification($loan->loadMissing('employee', 'loanType'), 'accounting'),
                );
            }
        } catch (\Throwable) {
            // Non-fatal
        }
    }

    /**
     * Notify the original HR approver that accounting has approved the loan.
     */
    private function notifyOfAccountingApproval(Loan $loan): void
    {
        try {
            $loan->loadMissing('employee', 'loanType');

            // Notify HR approver
            if ($loan->approved_by) {
                $hrApprover = User::find($loan->approved_by);
                $hrApprover?->notify(new LoanAccountingApprovedNotification($loan, 'hr'));
            }
        } catch (\Throwable) {
            // Non-fatal
        }
    }

    /**
     * Notify HR managers when a loan application is cancelled.
     */
    private function notifyOfLoanCancellation(Loan $loan): void
    {
        try {
            $loan->loadMissing('employee', 'loanType');

            // HR Managers — remove from their pending queue
            $hrManagers = User::permission('loans.approve')->get();
            if ($hrManagers->isNotEmpty()) {
                Notification::send($hrManagers, new LoanCancelledNotification($loan, 'hr'));
            }
        } catch (\Throwable) {
            // Non-fatal
        }
    }

    /**
     * Notify HR and Accounting managers that a loan has been written off (LN-009).
     */
    private function notifyOfLoanWriteOff(Loan $loan): void
    {
        try {
            $loan->loadMissing('employee', 'loanType');

            // HR Managers — must review for final pay deduction
            $hrManagers = User::permission('loans.approve')->get();
            if ($hrManagers->isNotEmpty()) {
                Notification::send($hrManagers, new LoanWrittenOffNotification($loan, 'hr'));
            }

            // Accounting Managers — may need a GL adjustment entry
            $acctgManagers = User::permission('loans.accounting_approve')->get();
            if ($acctgManagers->isNotEmpty()) {
                Notification::send($acctgManagers, new LoanWrittenOffNotification($loan, 'accounting'));
            }
        } catch (\Throwable) {
            // Non-fatal
        }
    }

    /**
     * LN-001: Assert no active loan of the same type exists for this employee.
     * Calamity loans are exempt (one per calamity event — tracked separately).
     *
     * @throws DomainException
     */
    private function assertNoActiveLoan(Employee $employee): void
    {
        $activeLoan = Loan::where('employee_id', $employee->id)
            ->whereIn('status', ['pending', 'approved', 'active'])
            ->with('loanType')
            ->first();

        if ($activeLoan !== null) {
            throw new DomainException(
                sprintf(
                    'Employee already has an active %s loan (#%s). It must be fully paid or settled before applying for a new one (LN-001).',
                    $activeLoan->loanType->name ?? 'loan',
                    $activeLoan->reference_no,
                ),
                'LN_DUPLICATE_ACTIVE_LOAN',
                422,
            );
        }
    }

    /**
     * LN-002: Assert principal is within allowed limits for the loan type.
     *
     * @throws DomainException
     */
    private function assertPrincipalWithinLimits(LoanType $loanType, int $principalCentavos): void
    {
        if ($principalCentavos < $loanType->min_amount_centavos) {
            throw new DomainException(
                sprintf(
                    'Principal ₱%s is below the minimum ₱%s for %s (LN-002).',
                    number_format($principalCentavos / 100, 2),
                    number_format($loanType->min_amount_centavos / 100, 2),
                    $loanType->name,
                ),
                'LN_PRINCIPAL_BELOW_MIN',
                422,
            );
        }

        if ($loanType->max_amount_centavos !== null && $principalCentavos > $loanType->max_amount_centavos) {
            throw new DomainException(
                sprintf(
                    'Principal ₱%s exceeds maximum ₱%s allowed for %s (LN-002).',
                    number_format($principalCentavos / 100, 2),
                    number_format($loanType->max_amount_centavos / 100, 2),
                    $loanType->name,
                ),
                'LN_PRINCIPAL_EXCEEDS_MAX',
                422,
            );
        }
    }

    /**
     * LN-003/LN-004: Government loan eligibility.
     *
     * SSS Loan    — requires ≥ 36 months of posted SSS contributions.
     * Pag-IBIG Loan — requires ≥ 24 months of posted Pag-IBIG contributions.
     *
     * Eligibility is determined from `payroll_government_contributions` which is
     * populated by the payroll engine starting Sprint 2.2. Employees with no
     * payroll history automatically fail the check for government loan types.
     */
    private function assertGovernmentLoanEligibility(Employee $employee, LoanType $loanType): void
    {
        if ($loanType->category !== 'government') {
            return;
        }

        $code = strtoupper($loanType->code);

        if (str_contains($code, 'SSS')) {
            $months = DB::table('payroll_government_contributions')
                ->where('employee_id', $employee->id)
                ->where('sss_ee_centavos', '>', 0)
                ->whereNotNull('contribution_period')
                ->distinct()
                ->count('contribution_period');

            if ($months < 36) {
                throw new DomainException(
                    message: "Employee does not meet SSS loan eligibility: requires 36 posted SSS contribution months, found {$months}.",
                    errorCode: 'LN_003_SSS_ELIGIBILITY',
                    httpStatus: 422,
                );
            }
        }

        if (str_contains($code, 'PAGIBIG') || str_contains($code, 'PAG_IBIG')) {
            $months = DB::table('payroll_government_contributions')
                ->where('employee_id', $employee->id)
                ->where('pagibig_ee_centavos', '>', 0)
                ->whereNotNull('contribution_period')
                ->distinct()
                ->count('contribution_period');

            if ($months < 24) {
                throw new DomainException(
                    message: "Employee does not meet Pag-IBIG loan eligibility: requires 24 posted Pag-IBIG contribution months, found {$months}.",
                    errorCode: 'LN_004_PAGIBIG_ELIGIBILITY',
                    httpStatus: 422,
                );
            }
        }
    }

    /**
     * Generate a unique reference number: LN-YYYY-NNNNNN
     */
    private function generateReferenceNo(): string
    {
        $year = date('Y');
        $last = Loan::withTrashed()
            ->where('reference_no', 'LIKE', "LN-{$year}-%")
            ->orderByDesc('reference_no')
            ->value('reference_no');

        $next = $last
            ? (int) substr((string) $last, -6) + 1
            : 1;

        return sprintf('LN-%s-%06d', $year, $next);
    }
}
