<?php

declare(strict_types=1);

namespace App\Support;

use Database\Seeders\RolePermissionSeeder;

/**
 * Extracts the "baseline" permission sets per role from the seeder.
 *
 * Used by the admin "Reset to defaults" endpoint so we don't have to
 * re-run the full seeder — we just sync the specific role.
 *
 * NOTE: Keep in sync with RolePermissionSeeder when adding new permissions.
 */
final class RolePermissionDefaults
{
    /** Roles that must never be deleted or have their core identity changed. */
    public const PROTECTED_ROLES = [
        'super_admin', 'admin', 'executive', 'vice_president',
        'manager', 'officer', 'head', 'staff',
        'vendor', 'client',
    ];

    /**
     * Return the default permission names for a given role.
     *
     * @return string[]|null  null if role has no seeder defaults
     */
    public static function forRole(string $roleName): ?array
    {
        $map = self::all();

        return $map[$roleName] ?? null;
    }

    /**
     * Full map: role_name => [permission_name, ...].
     *
     * super_admin is intentionally omitted — it always gets ALL permissions.
     *
     * @return array<string, string[]>
     */
    public static function all(): array
    {
        return [
            'admin' => [
                'system.manage_users', 'system.assign_roles', 'system.assign_departments',
                'system.unlock_accounts', 'system.edit_settings',
                'system.manage_rate_tables', 'system.manage_holidays', 'system.manage_ewt_atc',
                'system.reopen_fiscal_period', 'system.view_audit_log',
                'system.view_horizon', 'system.view_pulse', 'system.manage_backups',
                'vendors.view', 'customers.view',
            ],

            'executive' => [
                'employees.view',
                'attendance.view_team', 'overtime.view', 'overtime.executive_approve',
                'leaves.view_own', 'leaves.view_team', 'leaves.executive_approve',
                'loans.view_own', 'loans.view_department',
                'payroll.view_runs', 'payroll.view_own_payslip', 'payroll.download_own_payslip', 'payroll.view',
                'journal_entries.view', 'chart_of_accounts.view', 'fiscal_periods.view',
                'vendors.view', 'vendor_invoices.view', 'customers.view', 'customer_invoices.view',
                'reports.financial_statements', 'reports.gl', 'reports.trial_balance',
                'reports.ap_aging', 'reports.ar_aging', 'reports.bank_reconciliation',
                'budget.view', 'fixed_assets.view',
                'overtime.submit',
                'self.view_profile', 'self.view_attendance',
                'bank_accounts.view', 'bank_reconciliations.view',
                'procurement.purchase-request.view', 'procurement.purchase-order.view',
                'inventory.items.view', 'inventory.stock.view',
                'production.orders.view', 'qc.inspections.view', 'qc.ncr.view',
                'maintenance.view', 'mold.view',
            ],

            'vice_president' => [
                'employees.view', 'employees.view_team', 'employees.view_full_record',
                'approvals.vp.view', 'approvals.vp.approve',
                'payroll.view_runs', 'payroll.vp_approve',
                'payroll.view_own_payslip', 'payroll.download_own_payslip',
                'procurement.purchase-request.view', 'procurement.purchase-request.review',
                'procurement.purchase-order.view',
                'inventory.mrq.view', 'inventory.mrq.vp_approve',
                'journal_entries.view', 'chart_of_accounts.view', 'fiscal_periods.view',
                'vendors.view', 'vendor_invoices.view', 'vendor_invoices.approve',
                'customers.view', 'customer_invoices.view', 'customer_invoices.approve',
                'bank_accounts.view', 'bank_reconciliations.view',
                'reports.ap_aging', 'reports.ar_aging',
                'reports.financial_statements', 'reports.gl', 'reports.trial_balance',
                'reports.vat', 'reports.bank_reconciliation',
                'budget.view', 'budget.approve',
                'fixed_assets.view',
                'loans.view_department', 'loans.vp_approve',
                'recruitment.requisitions.approve', 'recruitment.hiring.approve',
                'inventory.items.view', 'inventory.stock.view',
                'procurement.goods-receipt.view',
                'production.orders.view', 'production.delivery-schedule.view',
                'qc.inspections.view', 'qc.ncr.view',
                'maintenance.view',
                'sales.order_review', 'sales.order_approve', 'sales.order_reject', 'sales.order_negotiate',
                'sales.order_vp_approve',
                'crm.leads.view', 'crm.opportunities.view',
                'sales.quotations.view', 'sales.orders.view', 'sales.pricing.view',
                'inventory.physical_count.view',
                'ap.payment_batches.view',
                'ar.dunning.view',
                'hr.training.view', 'hr.competency.view',
                'delivery.routes.view',
                'fixed_assets.transfer',
                'budget.forecast',
                'self.view_profile', 'self.view_attendance',
                'leaves.view_own', 'leaves.view_team',
                'overtime.view',
            ],

            'manager' => [
                'employees.view', 'employees.view_team', 'employees.view_full_record', 'employees.view_salary',
                'employees.view_unmasked_gov_ids', 'employees.view_masked_gov_ids',
                'employees.create', 'employees.update', 'employees.update_salary',
                'employees.activate', 'employees.suspend', 'employees.terminate',
                'employees.upload_documents', 'employees.download_documents',
                'employees.export', 'employees.manage_structure',
                'hr.full_access',
                'attendance.view_own', 'attendance.view_team', 'attendance.import_csv',
                'attendance.view_anomalies', 'attendance.resolve_anomalies', 'attendance.manage_shifts',
                'attendance.time_clock', 'attendance.corrections.submit', 'attendance.corrections.review',
                'attendance.work_locations.manage', 'attendance.work_locations.assign',
                'overtime.view', 'overtime.submit', 'overtime.approve', 'overtime.reject', 'overtime.supervise',
                'leaves.view_own', 'leaves.view_team', 'leaves.file_own', 'leaves.file_on_behalf',
                'leaves.cancel', 'leaves.head_approve', 'leaves.manager_approve', 'leaves.hr_approve', 'leaves.reject',
                'leaves.adjust_balance', 'leaves.configure_types', 'leaves.trigger_sil_monetization',
                'leave_balances.view', 'leave_balances.adjust', 'leave_balances.manage',
                'loans.view_own', 'loans.view_department', 'loans.apply',
                'loans.hr_approve', 'loans.accounting_approve', 'loans.view_ln007_log', 'loans.configure_types',
                'loans.manager_check', 'loans.officer_review',
                'recruitment.requisitions.view', 'recruitment.requisitions.create', 'recruitment.requisitions.edit',
                'recruitment.requisitions.submit', 'recruitment.requisitions.reject', 'recruitment.requisitions.cancel',
                'recruitment.requisitions.approve',
                'recruitment.postings.view', 'recruitment.postings.create', 'recruitment.postings.publish', 'recruitment.postings.close',
                'recruitment.applications.view', 'recruitment.applications.create', 'recruitment.applications.delete',
                'recruitment.applications.review', 'recruitment.applications.shortlist', 'recruitment.applications.reject',
                'recruitment.interviews.view', 'recruitment.interviews.schedule', 'recruitment.interviews.evaluate',
                'recruitment.offers.view', 'recruitment.offers.create', 'recruitment.offers.send',
                'recruitment.preemployment.view', 'recruitment.preemployment.verify',
                'recruitment.hiring.execute',
                'recruitment.reports.view', 'recruitment.candidates.view', 'recruitment.candidates.manage',
                'budget.view', 'budget.manage', 'budget.approve',
                'fixed_assets.view', 'fixed_assets.manage', 'fixed_assets.dispose',
                'journal_entries.view', 'journal_entries.create', 'journal_entries.update',
                'journal_entries.submit', 'journal_entries.post', 'journal_entries.reverse',
                'journal_entries.export',
                'chart_of_accounts.view', 'chart_of_accounts.manage',
                'fiscal_periods.view', 'fiscal_periods.manage',
                'vendors.view', 'vendors.manage', 'vendors.archive', 'vendors.accredit', 'vendors.suspend',
                'vendor_invoices.view', 'vendor_invoices.create', 'vendor_invoices.update',
                'vendor_invoices.submit', 'vendor_invoices.approve', 'vendor_invoices.reject',
                'vendor_invoices.record_payment', 'vendor_invoices.cancel', 'vendor_invoices.export',
                'vendor_payments.view', 'vendor_payments.create',
                'bir_2307.generate',
                'customers.view', 'customers.manage', 'customers.archive',
                'customer_invoices.view', 'customer_invoices.create', 'customer_invoices.update',
                'customer_invoices.approve', 'customer_invoices.cancel',
                'customer_invoices.override_credit', 'customer_invoices.receive_payment',
                'customer_invoices.write_off', 'customer_invoices.apply_payment', 'customer_invoices.export',
                'bank_accounts.view', 'bank_accounts.create', 'bank_accounts.update', 'bank_accounts.delete',
                'bank_reconciliations.view', 'bank_reconciliations.create', 'bank_reconciliations.certify',
                'reports.vat',
                'reports.financial_statements', 'reports.gl', 'reports.trial_balance',
                'reports.ap_aging', 'reports.ar_aging', 'reports.bank_reconciliation',
                'procurement.purchase-request.view', 'procurement.purchase-request.create',
                'procurement.purchase-request.note', 'procurement.purchase-request.check',
                'procurement.purchase-request.review', 'procurement.purchase-request.budget-check',
                'procurement.purchase-order.view', 'procurement.purchase-order.create', 'procurement.purchase-order.manage',
                'procurement.goods-receipt.view', 'procurement.goods-receipt.create', 'procurement.goods-receipt.confirm',
                'vendor_portal.view_orders', 'vendor_portal.update_fulfillment',
                'production.bom.view', 'production.delivery-schedule.view', 'production.orders.view',
                'production.orders.create', 'production.orders.release', 'production.orders.complete', 'production.orders.log_output',
                'qc.inspections.view', 'qc.inspections.create', 'qc.ncr.view', 'qc.ncr.create', 'qc.ncr.close', 'qc.templates.view',
                'maintenance.view', 'maintenance.manage',
                'mold.view', 'mold.manage', 'mold.log_shots',
                'delivery.view', 'delivery.manage',
                'inventory.items.view', 'inventory.items.create', 'inventory.items.edit',
                'inventory.stock.view', 'inventory.locations.view', 'inventory.locations.manage',
                'inventory.adjustments.create',
                'crm.leads.view', 'crm.leads.manage', 'crm.leads.convert',
                'crm.opportunities.view', 'crm.opportunities.manage',
                'sales.quotations.view', 'sales.quotations.create', 'sales.quotations.update',
                'sales.quotations.send', 'sales.quotations.accept', 'sales.quotations.manage',
                'sales.orders.view', 'sales.orders.confirm', 'sales.orders.cancel', 'sales.orders.manage',
                'sales.pricing.view',
                'inventory.physical_count.view', 'inventory.physical_count.manage',
                'inventory.transfers.manage',
                'ap.payment_batches.view', 'ap.payment_batches.create', 'ap.payment_batches.manage', 'ap.payment_batches.approve',
                'ar.dunning.view', 'ar.dunning.create', 'ar.dunning.send', 'ar.dunning.manage',
                'hr.training.view', 'hr.training.manage',
                'hr.competency.view', 'hr.competency.manage',
                'delivery.routes.view', 'delivery.routes.manage',
                'fixed_assets.transfer',
                'budget.forecast',
                'inventory.mrq.view', 'inventory.mrq.create', 'inventory.mrq.note', 'inventory.mrq.check',
                'inventory.mrq.review', 'inventory.mrq.vp_approve', 'inventory.mrq.fulfill',
                'payroll.view_own_payslip', 'payroll.download_own_payslip',
                'payroll.view_runs', 'payroll.manage_pay_periods',
                'payroll.initiate', 'payroll.hr_approve',
                'payroll.acctg_approve', 'payroll.acctg_reject',
                'payroll.hr_return',
                'payroll.disburse', 'payroll.download_bank_file',
                'payroll.publish', 'payroll.view_deduction_trace',
                'payroll.download_register', 'payroll.gov_reports',
                'reports.bir_2316', 'reports.bir_alphalist', 'reports.bir_1601c',
                'reports.sss_sbr2', 'reports.philhealth_rf1', 'reports.pagibig_mc',
                'self.view_profile', 'self.submit_profile_update', 'self.view_attendance',
                'payroll.view', 'payroll.submit', 'payroll.approve',
                'payroll.post', 'payroll.recall', 'payslips.view', 'payslips.download',
                'leaves.view', 'leaves.create', 'leave_balances.view', 'leave_balances.adjust',
                'loans.view', 'loans.create', 'loans.update', 'loans.approve', 'loans.reject',
                'loan_types.view', 'attendance.view', 'attendance.create', 'attendance.update',
                'attendance.delete', 'attendance.export', 'attendance.lock', 'attendance.unlock',
                'overtime.create', 'overtime.update',
            ],

            'officer' => [
                'journal_entries.view', 'journal_entries.create', 'journal_entries.update',
                'journal_entries.submit', 'journal_entries.post', 'journal_entries.reverse',
                'journal_entries.export',
                'chart_of_accounts.view', 'chart_of_accounts.manage',
                'fiscal_periods.view', 'fiscal_periods.manage',
                'vendors.view', 'vendors.manage', 'vendors.archive', 'vendors.accredit', 'vendors.suspend',
                'vendor_invoices.view', 'vendor_invoices.create', 'vendor_invoices.update', 'vendor_invoices.approve',
                'vendor_invoices.submit', 'vendor_invoices.reject', 'vendor_invoices.cancel',
                'vendor_invoices.record_payment', 'vendor_invoices.export',
                'vendor_payments.view', 'vendor_payments.create',
                'bir_2307.generate',
                'customers.view', 'customers.manage', 'customers.archive',
                'customer_invoices.view', 'customer_invoices.create', 'customer_invoices.update', 'customer_invoices.approve',
                'customer_invoices.cancel', 'customer_invoices.override_credit', 'customer_invoices.receive_payment',
                'customer_invoices.write_off', 'customer_invoices.apply_payment', 'customer_invoices.export',
                'bank_accounts.view', 'bank_accounts.create', 'bank_accounts.update', 'bank_accounts.delete',
                'bank_reconciliations.view', 'bank_reconciliations.create', 'bank_reconciliations.certify',
                'payroll.view_runs', 'payroll.view_own_payslip', 'payroll.download_own_payslip',
                'payroll.acctg_approve', 'payroll.acctg_reject',
                'payroll.disburse', 'payroll.download_bank_file',
                'payroll.publish', 'payroll.view_deduction_trace',
                'payroll.download_register', 'payroll.gov_reports',
                'loans.view_department',
                'budget.view',
                'procurement.purchase-request.budget-check',
                'fixed_assets.view',
                'reports.vat',
                'reports.bir_2316', 'reports.bir_alphalist', 'reports.bir_1601c',
                'reports.sss_sbr2', 'reports.philhealth_rf1', 'reports.pagibig_mc',
                'reports.financial_statements', 'reports.gl', 'reports.trial_balance',
                'reports.ap_aging', 'reports.ar_aging', 'reports.bank_reconciliation',
                'self.view_profile', 'self.view_attendance',
                'overtime.view', 'overtime.submit',
                'employees.view',
                'payroll.view', 'loans.view',
                'employees.view_team', 'employees.view_full_record', 'employees.view_masked_gov_ids',
                'employees.upload_documents', 'employees.download_documents',
                'attendance.view_team', 'attendance.view_anomalies', 'attendance.manage_shifts',
                'overtime.supervise', 'overtime.approve', 'overtime.reject',
                'leaves.view_team', 'leaves.file_on_behalf', 'leaves.approve', 'leaves.reject',
                'inventory.items.view', 'inventory.items.create', 'inventory.items.edit',
                'inventory.stock.view', 'inventory.locations.view',
                'inventory.mrq.view', 'inventory.mrq.create',
                'inventory.adjustments.create',
                'procurement.purchase-request.view', 'procurement.purchase-request.create',
                'procurement.purchase-request.note', 'procurement.purchase-request.check',
                'procurement.purchase-request.review',
                'procurement.purchase-order.view', 'procurement.purchase-order.create', 'procurement.purchase-order.manage',
                'procurement.goods-receipt.view', 'procurement.goods-receipt.create', 'procurement.goods-receipt.confirm',
                'production.bom.view', 'production.delivery-schedule.view', 'production.orders.view',
                'crm.leads.view', 'crm.leads.manage',
                'crm.opportunities.view', 'crm.opportunities.manage',
                'sales.quotations.view', 'sales.quotations.create', 'sales.quotations.update',
                'sales.quotations.send', 'sales.quotations.accept', 'sales.quotations.manage',
                'sales.orders.view', 'sales.orders.confirm', 'sales.orders.cancel', 'sales.orders.manage',
                'sales.pricing.view',
                'inventory.physical_count.view', 'inventory.physical_count.manage',
                'inventory.transfers.manage',
                'ap.payment_batches.view', 'ap.payment_batches.manage',
                'ar.dunning.view', 'ar.dunning.manage',
                'hr.training.view', 'hr.training.manage',
                'hr.competency.view',
                'delivery.routes.view',
                'fixed_assets.transfer',
                'budget.forecast',
                'recruitment.requisitions.view', 'recruitment.applications.view',
                'recruitment.applications.review', 'recruitment.applications.shortlist',
                'recruitment.interviews.view',
                'recruitment.candidates.view',
            ],

            'head' => [
                'employees.view', 'employees.view_team', 'employees.view_full_record', 'employees.view_masked_gov_ids',
                'employees.upload_documents', 'employees.download_documents',
                'attendance.view_team', 'attendance.view_anomalies', 'attendance.manage_shifts',
                'overtime.view', 'overtime.submit', 'overtime.supervise', 'overtime.approve', 'overtime.reject',
                'leaves.view_team', 'leaves.file_on_behalf', 'leaves.head_approve', 'leaves.approve', 'leaves.reject',
                'loans.view_department', 'loans.head_note', 'loans.apply',
                'payroll.view_runs',
                'inventory.items.view', 'inventory.stock.view', 'inventory.locations.view',
                'inventory.mrq.view', 'inventory.mrq.create', 'inventory.mrq.note',
                'inventory.adjustments.create',
                'procurement.purchase-request.view', 'procurement.purchase-request.create',
                'procurement.purchase-request.create-dept',
                'procurement.purchase-order.view', 'procurement.goods-receipt.view',
                'production.bom.view', 'production.delivery-schedule.view', 'production.orders.view',
                'production.orders.create', 'production.orders.release',
                'qc.templates.view', 'qc.inspections.view', 'qc.inspections.create',
                'qc.ncr.view', 'qc.ncr.create',
                'maintenance.view', 'maintenance.manage',
                'mold.view', 'mold.manage', 'mold.log_shots',
                'delivery.view', 'delivery.manage',
                'iso.view', 'iso.audit',
                'crm.tickets.view', 'crm.tickets.create', 'crm.tickets.reply', 'crm.tickets.manage',
                'crm.leads.view', 'crm.leads.manage', 'crm.leads.convert',
                'crm.opportunities.view', 'crm.opportunities.manage',
                'sales.order_review',
                'sales.quotations.view', 'sales.quotations.create', 'sales.quotations.update',
                'sales.quotations.send', 'sales.quotations.accept', 'sales.quotations.manage',
                'sales.orders.view', 'sales.orders.confirm', 'sales.orders.cancel', 'sales.orders.manage',
                'sales.pricing.view',
                'inventory.physical_count.view', 'inventory.physical_count.manage',
                'inventory.transfers.manage',
                'ap.payment_batches.view',
                'ar.dunning.view', 'ar.dunning.manage',
                'hr.training.view',
                'hr.competency.view',
                'delivery.routes.view', 'delivery.routes.manage',
                'fixed_assets.view', 'fixed_assets.transfer',
                'budget.view', 'budget.forecast',
                'journal_entries.view', 'chart_of_accounts.view',
                'vendors.view', 'customers.view',
                'self.view_profile', 'self.submit_profile_update', 'self.view_attendance',
                'leaves.view_own', 'leaves.file_own',
                'loans.view_own',
                'payroll.view_own_payslip', 'payroll.download_own_payslip',
                'attendance.view', 'leaves.view', 'loans.view', 'payroll.view',
            ],

            'staff' => [
                'self.view_profile', 'self.submit_profile_update', 'self.view_attendance',
                'employees.view_masked_gov_ids',
                'attendance.view_own', 'attendance.time_clock', 'attendance.corrections.submit',
                'overtime.view', 'overtime.submit',
                'leaves.view_own', 'leaves.file_own', 'leaves.cancel',
                'loans.view_own', 'loans.apply',
                'payroll.view_own_payslip', 'payroll.download_own_payslip',
                'payslips.view', 'payslips.download',
            ],

            'vendor' => [
                'vendor_portal.view_orders',
                'vendor_portal.update_fulfillment',
                'vendor_portal.manage_items',
                'vendor_portal.view_receipts',
            ],

            'client' => [
                'client_portal.view_dashboard',
                'client_portal.view_shop',
                'client_portal.view_orders',
                'crm.tickets.view',
                'crm.tickets.create',
                'crm.tickets.reply',
            ],
        ];
    }
}
